### ISSUE TITLE
[PE-D][Tester C] Unnecessarily complicated command format (view command)

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-1/tp#196]
Even after adding a contact using n/NAME and j/JOB, I need to retype those information when using View command

Can be optimised a lot by using index similar to edit command

![Screenshot 2024-11-08 at 4.40.11 PM.png](https://raw.githubusercontent.com/Shux347/ped/main/files/6afb3a80-9d22-44a5-b14a-ea9e4208c7b3.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Shux347/ped#4

**Comment by SQ77** [comment]
Feature suggestion: unable to change in v1.6
