### ISSUE TITLE
[PE-D][Tester D] Incorrect display of error message for edit

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-1/tp#197]
![image.png](https://raw.githubusercontent.com/ttzuche/pe/main/files/81b6ae06-398e-4c07-8e42-09c2b342f7eb.png)

When I tested out the functions with invalid indices -1, 0 and 10, only the one with positive integer gave me an error message that says candidate index provided is invalid. However, when I tested out with -1 and 0, I got back an invalid command format error message. I think to resolve this we can check the logic of the index first and throw the specific error when the index is invalid.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ttzuche/pe#5

**Comment by LemonDrew** [comment]
Error message is correct since it was clearly stated that parameters INDEX must be POSITIVE. Hence, any integers less than equal to 0 is considered a command format error since the user is not following the stated command format
